FROM node:16.15.1 as builder

COPY package*.json ./

RUN npm install --force

COPY . .

EXPOSE 8081

RUN npm run build




FROM nginx:alpine

COPY ./nginx.conf /etc/nginx/nginx.conf

RUN rm -rf /usr/share/nginx/html/*

COPY --from=builder /dist /usr/share/nginx/html

EXPOSE 80

ENTRYPOINT ["nginx", "-g", "daemon off;"]