name: "Destroy Dev Environment"

on:
  workflow_dispatch:
jobs:
  terraform:
   name: "Terraform Destroy env"
   runs-on: ubuntu-latest
   env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      TF_VAR_aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
      TF_VAR_aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
   steps:
   - name: Get code
     uses: actions/checkout@v3
     with:
        repository: 'mahdi-hamdii/dev-env-aws-cicd'
        ref: 'main'
        token: ${{ secrets.GH_TOKEN }}
        path: "/home/runner/work/cgbbox_admin_pipeline/cgbbox_admin_pipeline/dev-env-aws-cicd/"

   - name: Setup Terraform CLI
     uses: hashicorp/setup-terraform@v2 

   - name: Add the private key
     env:
        PRIVATE_KEY: ${{ secrets.CICD_PRIVATE_KEY }}
     run: echo "$PRIVATE_KEY" > /home/runner/work/cgbbox_admin_pipeline/cgbbox_admin_pipeline/dev-env-aws-cicd/private_key.pem 

   - name: init and  destroy
     working-directory: /home/runner/work/cgbbox_admin_pipeline/cgbbox_admin_pipeline/dev-env-aws-cicd/
     run: |
          terraform init
          terraform destroy -var 'private_key_path=/home/runner/work/cgbbox_admin_pipeline/cgbbox_admin_pipeline/dev-env-aws-cicd/private_key.pem' --auto-approve 